config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get '/:canton', to: 'people#index', constraints: { canton: /(AG|AR|AI|BL|BS|BE|FR|GE|GL|GR|JU|LU|NE|NW|OW|SH|SZ|SO|SG|TG|TI|UR|VS|VD|ZG|ZH)/ }

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "people#index"
    get 'apropos', to: 'static_pages#apropos'
    get 'detail', to: 'static_pages#detail'
    get 'imprint', to: 'static_pages#imprint'
    get 'privacy', to: 'static_pages#privacy'

    resources :people, only: [:index, :show], param: :slug, constraints: { slug: /(?!new$)[\w-]+/ } do
      collection do
        post 'filter_cantons'
        get 'get_canton_filter'
        post 'filter_parties'
        get 'get_party_filter'
        get :load_more
      end
    end


  end

end

app/models/person.rb
class Person < ApplicationRecord
    has_one_attached :image, dependent: :purge
    before_save :generate_slug
    has_many :votes
    has_many :votations, through: :votes
    has_many :businesses, through: :votations
    has_many :responses
    has_many :questions, through: :responses      

    def full_name
        "#{first_name} #{last_name}"
    end

    def to_param
        slug
    end

    def self.ransackable_attributes(auth_object = nil)
        ["canton", "created_at", "date_of_birth", "first_name", "group", "id", "last_name", "office", "party", "points", "slug", "reputation", "updated_at"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["businesses", "image_attachment", "image_blob", "questions", "responses", "votations", "votes"]
      end

    def calculate_points!

        # Enough votes for a rating?
        if (self.office == "NR" && self.votes.count < 15) or (self.office == "SR" && self.votes.count < 5)
            self.points = 0
            save
            return
        end

        # VOTES
        total_vote_points = 0
        total_possible_vote_points = 0
        # Iterate over all votes of the person.
        self.votes.each do |vote|
            # We count their votes if they have a position 0, 1, 2, or 4.
            if [0, 1, 2, 4].include?(vote.position)
                # Add the votation's weight to total_possible_vote_points
                total_possible_vote_points += vote.votation.weight

                # If the vote's position is 0 or 1, and it's identical to the ideal position, 
                # they get the full votation's weight as additional points
                if [0, 1].include?(vote.position) && vote.position == vote.votation.idealposition
                    total_vote_points += vote.votation.weight
                # If the vote's position is 2 or 4, they get half the votation's weight as additional points
                elsif [2, 4].include?(vote.position)
                    total_vote_points += vote.votation.weight / 2.0
                end
            end
        end
        if total_possible_vote_points == 0
            votes_percentage_achieved = 0
        else 
            votes_percentage_achieved = (total_vote_points / total_possible_vote_points.to_f) * 100
        end

        #SURVEYS
        survey = Survey.where(title_de:"2023").first
        
        total_survey_points = 0
        # Mapping between response and its corresponding points.
        response_points = {
            "Ja" => 4,
            "Eher Ja" => 3,
            "Keine Antwort" => 2,
            "Eher Nein" => 1,
            "Nein" => 0
        }
        
        total_questions_in_survey = survey.questions.count
        total_possible_survey_points = response_points["Ja"] * total_questions_in_survey  # Maximum possible points based on total questions in the survey
        # Iterate over all questions in the survey.
        survey.questions.each do |question|
            # Find the response of the person for this question.
            response = self.responses.find_by(question: question)
            # If the response exists, get its content, otherwise treat as "Keine Antwort"
            content = response ? response.content : "Keine Antwort"
            # Add the points from the mapping to the total
            total_survey_points += response_points[content]
        end
        # The percentage achieved
        survey_percentage_achieved = (total_survey_points / total_possible_survey_points.to_f) * 100
  
        # FINAL POINTS
        # votes count 2/3, survey counts 1/3
        self.points = ((2 * votes_percentage_achieved) + (1 * survey_percentage_achieved)) / 3
        
        # REPUTATION BOOST
        if self.reputation.present?
            self.points += (self.reputation * 5)
        end
        if self.points > 100
            self.points = 100 # can never go beyond 100
        end

        save
      end

    private

    def generate_slug
        self.slug = "#{first_name.parameterize}-#{last_name.parameterize}-#{canton}"
    end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  PEOPLE_PER_PAGE = 20

  # GET /people or /people.json
  def index
    @title = I18n.t("page_title")

    # sorting
    order = params[:order] || 'descending'
    @people = Person.order(Arel.sql("points #{order == 'ascending' ? 'ASC' : 'DESC'}"),
                        Arel.sql("COALESCE(reputation, -1) #{order == 'ascending' ? 'ASC' : 'DESC'}"),
                        Arel.sql("last_name ASC"),
                        Arel.sql("first_name ASC"))
                 .page(params[:page])
                 .per(PEOPLE_PER_PAGE)
    
    # search
    search_query = params[:search]
    if search_query.present?
      @people = @people.where("lower(first_name) LIKE ? OR lower(last_name) LIKE ?", "%#{search_query.downcase}%", "%#{search_query.downcase}%")
    end

    # filter by cantons
    selected_cantons = session[:selected_cantons] || []

    unless selected_cantons.empty? || selected_cantons.include?("All")
      @people = @people.where(canton: selected_cantons)
    end

    # filter by parties
    selected_parties = session[:selected_parties] || []
    unless selected_parties.empty? || selected_parties.include?("All")
      @people = @people.where(party: selected_parties)
    end

    respond_to do |format|
      format.html
      format.js do
        @has_more_people = @people.total_pages > @people.current_page
        render :index
      end
    end

  end

  def load_more
    @people = Person.order(points: order == 'ascending' ? :asc : :desc, last_name: :asc, first_name: :asc).page(params[:page]).per(PEOPLE_PER_PAGE)
    render layout: false
  end

  # GET /people/1 or /people/1.json
  def show
    @title = @person.first_name + " " + @person.last_name + " (" + @person.canton + ")"
    puts "========== Show action called =========="
  end

  # GET /people/new
  def new
    @person = Person.new
    puts "========== New action called =========="
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def filter_cantons
    if params[:selected_cantons].include?("All")
      session[:selected_cantons] = []
    else
      session[:selected_cantons] = params[:selected_cantons]
    end
    head :ok
  end
  
  def get_canton_filter
    selected_cantons = session[:selected_cantons] || []
    if selected_cantons.empty?
      selected_cantons = ["All"]
    end
    render json: { selected_cantons: selected_cantons }
  end

  def filter_parties
    if params[:selected_parties].include?("All")
      session[:selected_parties] = []
    else
      session[:selected_parties] = params[:selected_parties]
    end
    head :ok
  end

  def get_party_filter
    selected_parties = session[:selected_parties] || []
    if selected_parties.empty?
      selected_parties = ["All"]
    end
    render json: { selected_parties: selected_parties }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find_by(slug: params[:slug])
    end
    
    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :party, :group, :office, :canton, :date_of_birth, :points, :image)
    end
end

app/helpers/people_helper.rb
module PeopleHelper

    def rating_class_and_percentage(points)
        max = 100
        points = points.to_f # converts nil to 0.0
        percentage = (points / max) * 100
        rating_class =
          if percentage < 33.333
            'negative'
          elsif percentage < 66.666
            'neutral'
          else
            'positive'
          end
    
        [rating_class, percentage]
    end

end

app/views/people/_ajax.html.erb
<%= yield %>

app/views/people/_person.html.erb
<% rating_class, percentage = rating_class_and_percentage(person.points) %>
    <div class="list-item person-item">
      <%= link_to "", person_path(person), class:"overlay" %>
      <figure class="profile-rating-sm rating-<%= rating_class %>">
        <% if person.image.attached? %>
          <%= image_tag url_for(person.image), alt: person.full_name %>
        <% end %>
        <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" data-value="<%= percentage %>">
          <% if percentage > 0 %>
          <circle r="45" cx="50" cy="50" />
          <path class="meter" d="M5,50a45,45 0 1,0 90,0a45,45 0 1,0 -90,0" stroke-linecap="round" stroke-linejoin="round" stroke-dashoffset="282.78302001953125" stroke-dasharray="282.78302001953125" />
          <% end %>
        </svg>
      </figure>

      <div class="text">
        <span class="name"><%=person.first_name%> <%=person.last_name%></span>
        <div class="details">
          <span class="party"><%= person.party.present? ? t("parties.#{person.party}") : t("no_party") %></span>
          <span class="kanton"><%= t("cantons.#{person.canton}") %></span>
        </div>
        <% if percentage > 0 %>
          <div class="points-<%= rating_class %>">
            <span><%=number_with_precision(person.points, precision: 1, strip_insignificant_zeros: true)%> <%= t("person.points") %></span>
            <span class="reputation">
              <% if person.reputation.present? %>
                <% number_of_rockets = case person.reputation
                  when 1
                    1
                  when 1.5
                    2
                  when 2
                    3
                  else
                    0
                  end %>
                <% number_of_rockets.times do %>
                  <i class="ph ph-rocket-launch"></i>
                <% end %>
              <% end %>
            </span>
          </div>
        <% else %>
          <span><b><%= t("person.no_score") %></b> - <i><%= t("person.not_enough_votes") %></i></span>
        <% end %>

      </div>

      <button class="button-round"><i class="ph ph-caret-right"></i></button>
    </div>
    <!-- /list-item -->

app/views/people/_surveys.html.erb
<section class="detail-section">

<% total_responses = person.responses.where.not(content: nil).count %>
<% items_to_show = 15 %>
<% Survey.all.each do |survey| %>
  <h2><%= t("survey.title") %> <%= survey.title_de %></h2>
  <div class="vote-list">
    <% if total_responses > items_to_show %>
      <div class="hide-items-gradient-survey"></div>
    <% end %>
    <% responses_to_current_survey = [] %>

    <% survey.questions.each do |question| %>
      <% response = person.responses.includes(:question).find_by(question: question) %>

      <% if response && !response.content.nil? %>
        <% responses_to_current_survey << response %>

        <% 
        response_sentiment = 'negative'
        if response.content == 'Keine Antwort'
          response_sentiment = 'neutral'
        elsif response.content == 'Ja' or response.content == 'Eher Ja'
          response_sentiment = 'positive'
        end
        %>

        <div class="vote-item <%= 'hide-item-survey' if responses_to_current_survey.count > items_to_show %>">
          <span class="question"><%= question.send("title_#{I18n.locale}") %></span>

          <div class="badges">
            <span class="badge-<%=response_sentiment%>">
              <%=
                case response.content
                when "Eher Ja"
                  t("survey.responded_rather_yes")
                when "Ja"
                  t("survey.responded_yes")
                when "Eher Nein"
                  t("survey.responded_rather_no")
                when "Nein"
                  t("survey.responded_no")
                when "Keine Antwort"
                  t("survey.responded_no_answer")
                end
              %>
            </span>
          </div>
        </div>
      <% end %>
    <% end %>

    <% if responses_to_current_survey.empty? %>
      <div class="vote-item">
        <span class="question"><%=person.first_name %> <%=person.last_name %> <%= t('survey.no_responses') %>.</span>
      </div>
    <% end %>
  </div>
<% end %>

<% if total_responses > items_to_show %>
<a class="button-show button-show-survey" data-show-text="<%= t('show_more') %>" data-hide-text="<%= t('show_less') %>"><%=t("show_more")%></a>    
<% end %>

</section>

app/views/people/_votes.html.erb
<section class="detail-section">
  <h2><%= t("person.votes") %></h2>

  <div class="vote-list">
    <div class="hide-items-gradient"></div>

    <% person.votes.each_with_index do |vote, index| %>

      <% 
      vote_sentiment = 'negative'
      if vote.position == 2 or vote.position == 3 or vote.position == 4 or vote.position == 5
        vote_sentiment = 'neutral'
      elsif vote.position == vote.votation.idealposition
        vote_sentiment = 'positive'
      end
      %>
      <div class="vote-item <%= 'hide-item' if index > 3 %>">
      <%= link_to vote.business.send("link_#{I18n.locale}") do %>
        <%=t("business.type.#{vote.business.business_type}")%>: <%= vote.business.send("title_#{I18n.locale}") %>
        <i class="ph ph-arrow-square-out"></i>
      <% end %>


        <p><%= vote.votation.send("explanation_#{I18n.locale}") %></p>

        <div class="badges">
          <div>
            <span class="badge-<%= vote_sentiment %>"><%= t("votation.weight") %>: <%=vote.votation.weight%></span>
            <span class="badge-<%= vote_sentiment %>">
            <%=
            if vote.position == 0
              t("votation.voted_no")
            elsif vote.position == 1
              t("votation.voted_yes")
            elsif vote.position == 2
              t("votation.voted_abstention")
            elsif vote.position == 3
              t("votation.voted_absent_excused")
            elsif vote.position == 4
              t("votation.voted_absent")
            elsif vote.position == 5
              t("votation.presidency")
            end
            %>
            </span>
          </div>

          <span class="badge"><%= t("votation.business") %>: <%=vote.votation.business.shortnumber%></span>
          <span class="badge"><%= t("votation.vote") %>: <%=vote.votation.reference%></span>

        </div>
      </div>
    <% end %> 

  </div>
  <!-- /vote-list -->

  <a class="button-show" data-show-text="<%= t('show_more') %>" data-hide-text="<%= t('show_less') %>"><%=t("show_more")%></a>

</section>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<div class="ranking-list">
  <div class="content-center" id="people-container">

  <% if @people.any? %>
      <%= render partial: "person", collection: @people %>
    <% else %>
      <div class="list-message">
        <i class="icon ph ph-file-x-thin"></i>
        <p>
        <%= t("no_results") %>
        </p>
        </div>
      </div>
    <% end %>
 
</div>

app/views/people/index.js.erb
$('#people-container').append('<%= j render @people %>');
radialBar();
<% if @has_more_people %>
  window.hasMorePeople = true;
<% else %>
  window.hasMorePeople = false;
<% end %>

app/views/people/load_more.js.erb
$("#people-container").append('<%= j render(@people) %>');
$("#loading").hide();

<% if @people.next_page %>
  $(window).data("next-page", <%= @people.next_page %>);
<% else %>
  $(window).data("next-page", null);
<% end %>

app/views/people/show.html.erb
<% rating_class, percentage = rating_class_and_percentage(@person.points) %>
<div class="detail">
      <div class="content-center">
        <div class="col">
          <header class="detail-header">
            <figure class="profile-rating rating-<%= rating_class %>">
            <% if @person.image.attached? %>
            <%= image_tag url_for(@person.image), alt: @person.full_name %>
            <% end %>
              <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" data-value="<%= percentage %>">
                <% if percentage > 0 %>
                <circle r="45" cx="50" cy="50" />
                <path class="meter" d="M5,50a45,45 0 1,0 90,0a45,45 0 1,0 -90,0" stroke-linecap="round" stroke-linejoin="round" stroke-dashoffset="282.78302001953125" stroke-dasharray="282.78302001953125" />
                <% end %>
              </svg>
            </figure>

            <div class="text">
              <h1 class="name"><%=@person.first_name%> <%=@person.last_name%></h1>
              <div class="details">
                <span class="party"><%= @person.party.present? ? t("parties.#{@person.party}") : t("no_party") %></span>
                <span class="kanton"><%= t("cantons.#{@person.canton}") %></span>
              </div>
              <% if percentage > 0 %>
                <div class="points-<%= rating_class %>">
                  <span><%=number_with_precision(@person.points, precision: 1, strip_insignificant_zeros: true)%> <%= t("person.points") %></span>
                  <span class="reputation">
                    <% if @person.reputation.present? %>
                      <% number_of_rockets = case @person.reputation
                        when 1
                          1
                        when 1.5
                          2
                        when 2
                          3
                        else
                          0
                        end %>
                      <% number_of_rockets.times do %>
                        <i class="ph ph-rocket-launch"></i>
                      <% end %>
                    <% end %>
                  </span>
                </div>
              <% else %>
              <span><b><%= t("person.no_score") %></b> - <i><%= t("person.not_enough_votes") %></i></span>
              <% end %>
            </div>
          </header>
          <!-- /detail-header -->

          <section class="detail-section">
            <h2><%= t("person.personal_info") %></h2>

            <dl>
              <dt><%= t("person.office") %></dt>
              <dd><%= @person.office.present? ? t("offices.#{@person.office}") : "" %></dd>
              <dt><%= t("person.canton") %></dt>
              <dd><%= t("cantons.#{@person.canton}") %></dd>
              <dt><%= t("person.party") %></dt>
              <dd><%= @person.party.present? ? t("parties.#{@person.party}") : t("no_party") %></dd>
              <dt><%= t("person.group") %></dt>
              <dd><%= @person.group.present? ? t("groups.#{@person.group}") : "" %></dd>
              <dt><%= t("person.birthdate") %></dt>
              <dd><%= @person.date_of_birth&.strftime("%d. %m. %Y") %></dd>
            </dl>

          </section>
          <!-- /detail-section -->


        </div>
        <!-- /col -->

        <div class="col">
          <%= render partial: 'votes', locals: { person: @person } %>
          
          <!-- /detail-section -->

          <%= render partial: 'surveys', locals: { person: @person } %>

          <!-- /detail-section -->

        </div>
        <!-- /col -->

      </div>
    </div>
    <!-- /detail -->