config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get '/:canton', to: 'people#index', constraints: { canton: /(AG|AR|AI|BL|BS|BE|FR|GE|GL|GR|JU|LU|NE|NW|OW|SH|SZ|SO|SG|TG|TI|UR|VS|VD|ZG|ZH)/ }

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    root "people#index"
    get 'apropos', to: 'static_pages#apropos'
    get 'detail', to: 'static_pages#detail'
    get 'imprint', to: 'static_pages#imprint'
    get 'privacy', to: 'static_pages#privacy'

    resources :people, only: [:index, :show], param: :slug, constraints: { slug: /(?!new$)[\w-]+/ } do
      collection do
        post 'filter_cantons'
        get 'get_canton_filter'
        post 'filter_parties'
        get 'get_party_filter'
        get :load_more
      end
    end


  end

end

app/views/layouts/_footer.html.erb
<footer class="site-footer">
<div class="content-center">
  <ul class="social-links">
    <li><a href="https://www.facebook.com/chplusplus" class="facebook"><i class="icon ph ph-facebook-logo"><span class="sr-only">Facebook</span></i></a></li>
    <li><a href="https://www.linkedin.com/company/chplusplus/" class="linkedin"><i class="icon ph ph-linkedin-logo"><span class="sr-only">LinkedIn</span></i></a></li>
    <li><a href="https://mastodon.social/@chplusplus@techhub.social"><img src="<%=asset_url('mastodon-logo.svg')%>" alt="Mastodon"></a></li>
    <li><a href="https://twitter.com/chplusplus" class="twitter"><i class="icon ph ph-twitter-logo"><span class="sr-only">Twitter</span></i></a></li>
    <li><a href="https://www.youtube.com/channel/UCslsQ44lO2voIQCwl-ysFCA" class="youtube"><i class="icon ph ph-youtube-logo"><span class="sr-only">YouTube</span></i></a></li>
  </ul>

  <ul class="legal">
    <li>&copy; 2023 CH++</li>
    <li><%= link_to t("navigation.imprint"), imprint_path %></li>
    <li><%= link_to t("navigation.privacy"), privacy_path %></li>
  </ul>
</div>
</footer>
<!-- /site-footer -->

app/views/layouts/_header.html.erb
<header class="navbar">
    <a href="https://www.futuretechrating.ch/<%= I18n.locale %>" class="banner">
    <span class="banner-text"><%=t("banner_text")%></span><i class="icon ph ph-arrow-up-right"></i>
    </a>
  <div class="content-center">
    <div class="brand">
    <%= link_to people_path, class:"logo" do %>
      <span class="sr-only">CH++</span>
    <% end %>
    </div>

    <ul class="nav-main">
      <li><%= link_to t("navigation.home"), people_path, class: active_class_for_home %></li>
      <li><%= link_to t("navigation.how_it_works"), detail_path, class: "#{'active' if current_page?(detail_path)}" %></li>
      <li><%= link_to t("navigation.about"), apropos_path, class: "#{'active' if current_page?(apropos_path)}" %></li>
    </ul>



    <div class="language-selector">
      <button class="language-button"><%= I18n.locale.upcase %></button>

      <div id="language-dropdown" class="language-dropdown">
        <ul>
          <li>
            <%= link_to "Deutsch <i class='icon ph ph-check-circle-fill'></i>".html_safe, url_for(locale: 'de'), class: I18n.locale == :de ? 'active' : '' %>
          </li>
          <li>
            <%= link_to "Français <i class='icon ph ph-check-circle-fill'></i>".html_safe, url_for(locale: 'fr'), class: I18n.locale == :fr ? 'active' : '' %>
          </li>
        </ul>
      </div>
    </div>

    <button class="button-menu"><i class="icon ph ph-list"><span class="sr-only">Menu</span></i></button>
  </div>
</header>
<!-- /navbar -->

<nav class="mobile-nav">
  <button class="nav-close"><i class="icon ph ph-x"><span class="sr-only">Close</span></i></button>
  <ul class="nav-list">
    <li>
    <%= link_to t("navigation.home"), people_path %>
    </li>
    <li>
    <%= link_to t("navigation.how_it_works"), detail_path %>
    </li>
    <li>
      <%= link_to t("navigation.about"), apropos_path %>
    </li>
  </ul>

  <ul class="social-links">
    <li><a href="https://www.facebook.com/chplusplus" class="facebook"><i class="icon ph ph-facebook-logo"><span class="sr-only">Facebook</span></i></a></li>
    <li><a href="https://www.linkedin.com/company/chplusplus/" class="linkedin"><i class="icon ph ph-linkedin-logo"><span class="sr-only">LinkedIn</span></i></a></li>
    <li><a href="https://mastodon.social/@chplusplus@techhub.social"><img src="<%=asset_url('mastodon-logo-white.svg')%>" alt="Mastodon"></a></li>
    <li><a href="https://twitter.com/chplusplus" class="twitter"><i class="icon ph ph-twitter-logo"><span class="sr-only">Twitter</span></i></a></li>
    <li><a href="https://www.youtube.com/channel/UCslsQ44lO2voIQCwl-ysFCA" class="youtube"><i class="icon ph ph-youtube-logo"><span class="sr-only">YouTube</span></i></a></li>
  </ul>
</nav>
<!-- /mobile-nav -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <link rel="icon" type="image/svg+xml" href="<%=asset_url('favicon.svg')%>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="title" content="<%= @title %>">
    <meta name="description" content="">
    <meta property="og:type" content="website">
    <meta property="og:url" content="">
    <meta property="og:title" content="<%= @title %>">
    <meta property="og:description" content="">
    <meta property="og:image" content="">
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="">
    <meta property="twitter:title" content="<%= @title %>">
    <meta property="twitter:description" content="">
    <meta property="twitter:image" content="">
    <meta charset="UTF-8">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/@phosphor-icons/web@2.0.3/src/regular/style.css">
    <%= javascript_include_tag "https://code.jquery.com/jquery-3.6.0.min.js" %>

    <%= javascript_importmap_tags %>
    <script defer data-domain="techrating.ch" src="https://plausible.io/js/script.js"></script>

  </head>

  <body id="<%=controller_name%>_<%=action_name%>" data-turbo-action="<%='replace' if controller_name == 'people' && action_name == 'index' %>">
    <%= render 'layouts/header' %>  

    <% if controller_name == 'people' && action_name == 'index' %>
      <div id="modal-kantons" class="modal-container" data-filter-cantons-url="<%= filter_cantons_people_path %>" data-get-canton-filter-url="<%= get_canton_filter_people_path %>">
        <div class="modal">
          <div class="modal-header">
            <h3><%= t("modal.cantons.title") %></h3>
            <a href="#" class="close-kantons"><i class="icon ph ph-x"><span class="sr-only">Close</span></i></a>
          </div>

          <div class="modal-body">
            <div class="checkbox-list">
              <label class="checkbox-container all-canton-label"><strong><%= t("modal.cantons.all") %></strong>
              <input type="checkbox" id="all-canton-checkbox" checked>
              <span class="checkmark"></span>
              </label>

              <% canton_codes = I18n.t("cantons") %>
                <% canton_codes.each do |code, name| %>
                  <label class="checkbox-container"><%= name %> (<%= code %>)
                    <input type="checkbox">
                    <span class="checkmark"></span>
                  </label>
                <% end %>
            </div>
          </div>

          <div class="modal-footer">
            <a href="#" class="button-text"><%= t("modal.cantons.deselect") %></a>
            <a href="#" class="button-primary"><%= t("modal.cantons.apply") %></a>
          </div>
        </div>
      </div>
      <!-- /modal-kantons -->

      <div id="modal-parteiens" class="modal-container" data-get-party-filter-url="<%= get_party_filter_people_path %>" data-filter-parties-url="<%= filter_parties_people_path %>">
        <div class="modal">
          <div class="modal-header">
            <h3><%= t("modal.parties.title") %></h3>
            <a href="#" class="close-parteiens"><i class="icon ph ph-x"><span class="sr-only">Close</span></i></a>
          </div>

          <div class="modal-body">
            <div class="checkbox-list">
              <label class="checkbox-container"><strong><%= t("modal.parties.all") %></strong>
              <input type="checkbox" class="all-parties" id="all-party-checkbox" value="All" checked>
                <span class="checkmark"></span>
              </label>

              <% party_codes = I18n.t("parties") %>
              <% party_codes.each do |code, name| %>
                <label class="checkbox-container"><%= name %>
                  <input type="checkbox" class="party-checkbox" value="<%= code %>">
                  <span class="checkmark"></span>
                </label>
              <% end %>
            </div>
          </div>

          <div class="modal-footer">
            <a href="#" class="button-text"><%= t("modal.parties.deselect") %></a>
            <a href="#" class="button-primary apply-button"><%= t("modal.parties.apply") %></a>
          </div>
        </div>
      </div>
      <!-- /modal-parties -->
    <% end %>
    
    <main>
      <% unless controller_name == 'people' && action_name == 'show' %>
        <div class="masthead-index">
          <div class="content-center">
            <h1><%= @title %></h1>
            <% if controller_name == 'people' && action_name == 'index' %>
              <div class="masthead-actions">
              <form action="<%= people_path %>" method="get" id="search-form">
                <input type="text" name="search" class="input-search" placeholder="<%= t("navigation.search") %>" id="search-input" value="<%= params[:search] %>" data-people-url="<%= people_path(format: :js) %>">
                <input type="hidden" name="order" id="order-input" value="<%= params[:order] %>">
                <input type="submit" value="Search" style="display: none;">
              </form>
                <div class="button-container" id="kantons">
                  <div id="cantons_indicator" class="indicator">22</div>
                  <a href="#modal-kantons" class="button-primary"><i class="icon ph ph-sliders"></i><%= t("navigation.cantons") %></a>
                </div>
          
                <div class="button-container" id="parteiens">
                  <div id="parties_indicator" class="indicator">22</div>
                  <a href="#modal-parteien" class="button-primary"><i class="icon ph ph-sliders"></i><%= t("navigation.parties") %></a>
                </div>
          
                <div class="sort-button-container"
                data-sort-by-points-ascending-url="<%= people_path(order: 'ascending', search: params[:search]) %>"
                data-sort-by-points-descending-url="<%= people_path(order: 'descending', search: params[:search]) %>">
              
                  <a href="#" class="button-primary"><i class="icon ph ph-sort-ascending"></i><%= t("navigation.sort") %></a>
          
                  <div id="sort-dropdown" class="sort-dropdown">
                    <ul>
                      <li><a href="#" class="option1 active"><%= t("modal.sort.descending") %> <i class="icon ph ph-check-circle-fill"></i></a></li>
                      <li><a href="#" class="option2"><%= t("modal.sort.ascending") %> <i></i></a></li>
                    </ul>
                  </div>
          
                </div>
                
              </div>
              <!-- /masthead-actions -->
            <% end %>
          </div>
        </div>
        <!-- /masthead -->
      <% end %>
      <%= yield %>
    </main>
    <!-- /main -->

    <%= render 'layouts/footer' %>
  </body>
</html>